#!/usr/bin/env python3
"""Embed every cn-practice/*.py script into cn-exam-prep/data/code.js as window.CODE[name].

The site shows script sources inline; embedding them as a JS file keeps it working from
file:// (no fetch, no CORS). Re-run after editing any script:  python3 tools/build_code.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
src_dir = ROOT / "cn-practice"
out = ROOT / "cn-exam-prep" / "data" / "code.js"

lines = ["// AUTO-GENERATED by tools/build_code.py — do not edit by hand.", "window.CODE = window.CODE || {};"]
for f in sorted(src_dir.glob("*.py")):
    lines.append("window.CODE[%s] = %s;" % (json.dumps(f.name), json.dumps(f.read_text(encoding="utf-8"))))
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("embedded %d scripts into %s" % (len(lines) - 2, out.relative_to(ROOT)))
