// REFERENCE EXAMPLE for unit authors: one section that shows every block type and every question type.
// It is NOT loaded by the site. Copy the shapes exactly. Note: every LaTeX backslash is doubled.
window.UNITS = window.UNITS || {};
window.UNITS["unit99"] = {
  id: "unit99", num: 99, day: 1,
  title: "Example Unit — Transmission vs Propagation Delay",
  lectures: "Lecture 2 · WB-L02",
  overview: "<p>Every exam asks you to separate the time to <b>push bits onto the wire</b> ($L/R$) from the time for a bit to <b>travel</b> ($d/s$). Get the units right and these are free marks.</p>",
  sections: [
    {
      id: "99-A",
      title: "Transmission & Propagation Delay",
      badge: "class",
      source: "WB-L02 p16–19",
      covers: ["99.1"],
      blocks: [
        { type: "intuition", title: "Toll booth vs highway",
          html: "<p><b>Analogy.</b> Ten cars queue at a toll booth that serves one car every 12 s: the last car leaves 120 s after the first arrives. That is <b>transmission</b>: it depends on the size of the caravan and the speed of the booth. Driving 100 km to the next booth at 100 km/h takes 1 h whatever the caravan size. That is <b>propagation</b>.</p>" +
                "<p><b>Definition (Kurose &amp; Ross §1.4).</b> Transmission delay $d_{trans} = L/R$, where $L$ is the packet length in bits and $R$ is the link rate in bit/s. Propagation delay $d_{prop} = d/s$, where $d$ is the link length and $s$ is the propagation speed ($\\approx 2\\times10^8$ m/s in fibre or copper).</p>" },
        { type: "callout", kind: "slidefix", title: "WB-L02 p19 satellite example",
          html: "<p>The slide calls the ≈240 ms GEO delay a <i>round trip</i>. It is the <b>one-way</b> ground→satellite→ground path ($2\\times35{,}786$ km). A request plus its reply ≈ 480 ms.</p>" },
        { type: "figure", caption: "Transmission (pushing bits out) vs propagation (bits travelling).",
          html: "<svg viewBox='0 0 520 120' width='100%'><rect x='10' y='40' width='80' height='40' rx='6' fill='none' stroke='var(--accent)' stroke-width='2'/><text x='50' y='65' text-anchor='middle' fill='currentColor' font-size='13'>Host A</text><rect x='430' y='40' width='80' height='40' rx='6' fill='none' stroke='var(--accent)' stroke-width='2'/><text x='470' y='65' text-anchor='middle' fill='currentColor' font-size='13'>Host B</text><line x1='90' y1='60' x2='430' y2='60' stroke='var(--muted)' stroke-width='3'/><text x='130' y='32' fill='var(--warn)' font-size='12'>L/R: push L bits at R bit/s</text><text x='300' y='100' fill='var(--ok)' font-size='12'>d/s: travel distance d at speed s</text></svg>" },
        { type: "packet", title: "UDP header (RFC 768) — packet block example", width: 32,
          fields: [ { name: "Source port", bits: 16, note: "sender's port (ephemeral for clients)" },
                    { name: "Destination port", bits: 16, note: "e.g. 53 for DNS" },
                    { name: "Length", bits: 16, note: "header + data in bytes, minimum 8" },
                    { name: "Checksum", bits: 16, note: "1's-complement sum over pseudo-header + UDP header + data" } ],
          caption: "8 bytes in total." },
        { type: "seq", left: "Sender", right: "Receiver", caption: "Stop-and-wait with one loss (seq example).",
          events: [ { from: "L", label: "DATA seq=0" }, { from: "R", label: "ACK 1" },
                    { from: "L", label: "DATA seq=1", lost: true }, { gap: true, note: "timeout expires, retransmit" },
                    { from: "L", label: "DATA seq=1 (retx)" }, { from: "R", label: "ACK 0" } ] },
        { type: "chart", title: "cwnd per RTT (chart example)", xLabel: "Transmission round (RTT)", yLabel: "cwnd (MSS)",
          x: [1, 2, 3, 4, 5, 6, 7], series: [ { name: "cwnd", y: [1, 2, 4, 8, 9, 10, 5] } ],
          hlines: [ { y: 8, label: "ssthresh = 8" } ], marks: [ { x: 7, label: "3 dup ACKs" } ] },
        { type: "table", head: ["Rate R", "L = 8000 bits", "d_trans"],
          rows: [ ["2 Mbps", "8000 b", "4 ms"], ["4 Mbps", "8000 b", "2 ms"], ["8 Mbps", "8000 b", "1 ms"] ],
          caption: "WB-L02 p17 table." },
        { type: "derivation", title: "Total delay of one packet over one link",
          steps: [ { tex: "d_{total} = d_{proc} + d_{queue} + d_{trans} + d_{prop}", why: "A packet pays all four delays at each hop." },
                   { tex: "d_{total} \\approx \\frac{L}{R} + \\frac{d}{s}", why: "On an idle link, queuing is 0 and processing is microseconds, so both are dropped." },
                   { tex: "d_{total} = \\frac{8000}{2\\times10^{6}} + \\frac{2\\times10^{5}}{2\\times10^{8}}", why: "Substitute L = 8000 b, R = 2 Mbps, d = 200 km = 2×10^5 m, s = 2×10^8 m/s." },
                   { tex: "d_{total} = 4\\,\\text{ms} + 1\\,\\text{ms} = 5\\,\\text{ms}", why: "Convert each term from seconds to milliseconds (multiply by 1000)." } ] },
        { type: "cheat", items: [ "$d_{trans} = L/R$: depends on packet size and link rate", "$d_{prop} = d/s$: depends on distance and medium, <b>not</b> on packet size", "1 byte = 8 bits; 1 Mbps = $10^6$ bit/s; 1 KB in networking problems usually means 1000 B unless the question says KiB" ] },
        { type: "worked", title: "8000-bit packet over 200 km of fibre", tag: "University-Midsem-style",
          problem: "<p>Host A sends an 8000-bit packet to B over a single 2 Mbps fibre link 200 km long ($s = 2\\times10^8$ m/s). How long until B has the whole packet?</p>",
          steps: [ { tex: "d_{trans} = \\frac{8000}{2\\times10^6} = 0.004\\,\\text{s}", why: "The last bit leaves A after L/R." },
                   { tex: "d_{prop} = \\frac{200\\times10^3}{2\\times10^8} = 0.001\\,\\text{s}", why: "That last bit then needs d/s to reach B." },
                   { text: "Add: 4 ms + 1 ms.", why: "B has the whole packet when the last bit arrives." } ],
          answer: "<b>5 ms</b>" },
        { type: "code", file: "Unit02_delays.py", level: "low", title: "Delay calculator with explicit unit conversion" },
        { type: "code", file: "Unit02_delays.py", level: "high", title: "(each unit needs one low and one high script)" },
        { type: "traps", items: [ "Bits vs bytes: a 1500-<b>byte</b> packet is 12,000 bits.", "Propagation does not depend on packet size.", "Mbps uses $10^6$, not $2^{20}$." ] }
      ],
      practice: [
        { id: "u99-A-1", type: "mcq", tag: "University-Midsem-style", topic: "99.1",
          q: "<p>Doubling the link rate $R$ changes which delay?</p>",
          options: ["Propagation only", "Transmission only", "Both", "Neither"], answer: 1,
          why: ["$d/s$ has no $R$ in it.", "$L/R$ halves when $R$ doubles.", "Propagation is unchanged.", "Transmission does change."],
          explain: "<p>Only $d_{trans}=L/R$ contains $R$.</p>" },
        { id: "u99-A-2", type: "msq", tag: "GATE-style", topic: "99.1",
          q: "<p>Which quantities affect propagation delay? (Select all that apply.)</p>",
          options: ["Link length", "Packet size", "Medium (signal speed)", "Link bandwidth"], answer: [0, 2],
          why: ["d is in d/s.", "L appears only in L/R.", "s is in d/s.", "R appears only in L/R."],
          explain: "<p>$d_{prop}=d/s$.</p>" },
        { id: "u99-A-3", type: "num", tag: "University-Midsem-style", topic: "99.1",
          q: "<p>A 1500-<b>byte</b> packet is sent on a 10 Mbps link. Transmission delay in <b>ms</b>, rounded to 1 decimal?</p>",
          answer: 1.2, tol: 0.05, unit: "ms", verify: "round(1500*8/10e6*1000, 1)",
          formula: "d_{trans} = \\frac{L}{R}",
          steps: [ { tex: "L = 1500 \\times 8 = 12000\\,\\text{bits}", why: "Convert bytes to bits." },
                   { tex: "d_{trans} = \\frac{12000}{10\\times10^6} = 1.2\\times10^{-3}\\,\\text{s} = 1.2\\,\\text{ms}", why: "Divide by the rate, then convert to ms." } ] },
        { id: "u99-A-4", type: "text", tag: "University-Midsem-style", topic: "99.1",
          q: "<p>Predict the exact output.</p>", code: "L, R = 8000, 2_000_000\nprint(f\"{L / R * 1000:.1f} ms\")",
          answer: "4.0 ms", runCheck: true,
          explain: "<p>8000/2,000,000 = 0.004 s, which is 4.0 ms.</p>" },
        { id: "u99-A-5", type: "write", tag: "University-Midsem-style", topic: "99.1",
          q: "<p>Write <code>total_delay(L_bits, R_bps, d_m, s_mps)</code> that returns the one-hop delay in milliseconds.</p>",
          starter: "def total_delay(L_bits, R_bps, d_m, s_mps):\n    pass\n",
          solutionFile: "Unit02_delays.py",
          rubric: ["Computes L/R and d/s in seconds", "Adds them and multiplies by 1000", "Returns 5.0 for (8000, 2e6, 2e5, 2e8)"],
          explain: "<p>See the model solution.</p>" }
      ]
    }
  ]
};
